---
- hosts: mywebservers
  become: yes
  tasks:
   - name: install webserver on ubuntu nodes
     apt:
      name: "{{mywebpacnonUbuntu}}"
      state: present
     when: ansible_os_family == "Debian"

   - name: i want to start webserver on ubuntu nodes
     service:
      name: "{{mywebpacnonUbuntu}}"
      state: started